---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker-app
  template:
    metadata:
      labels:
        app: worker-app
    spec:
      containers:
      - name: worker-app-container
        image: daring-cyclops-worker:1
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 6379
        env:
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: redis-secret
                key: redis-password

#          - name: REDIS_URL 
#            valueFrom:
#              configMapKeyRef:
#                name: app-configmap 
#               key: redis-service 
