---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: manager
spec:
  replicas: 1
  selector:
    matchLabels:
      name: manager
  template:
    metadata:
      labels:
        name: manager
    spec:
      containers:
      - name: application
        image: manager
        imagePullPolicy: IfNotPresent
